/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CRF service. Represents a row in the &quot;EC_CRF&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.CRFModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.CRFImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see CRF
 * @generated
 */
@ProviderType
public interface CRFModel
	extends BaseModel<CRF>, MVCCModel, ShardedModel, StagedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crf model instance should use the {@link CRF} interface instead.
	 */

	/**
	 * Returns the primary key of this crf.
	 *
	 * @return the primary key of this crf
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crf.
	 *
	 * @param primaryKey the primary key of this crf
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this crf.
	 *
	 * @return the mvcc version of this crf
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this crf.
	 *
	 * @param mvccVersion the mvcc version of this crf
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this crf.
	 *
	 * @return the uuid of this crf
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this crf.
	 *
	 * @param uuid the uuid of this crf
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the crf ID of this crf.
	 *
	 * @return the crf ID of this crf
	 */
	public long getCrfId();

	/**
	 * Sets the crf ID of this crf.
	 *
	 * @param crfId the crf ID of this crf
	 */
	public void setCrfId(long crfId);

	/**
	 * Returns the group ID of this crf.
	 *
	 * @return the group ID of this crf
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this crf.
	 *
	 * @param groupId the group ID of this crf
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this crf.
	 *
	 * @return the company ID of this crf
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this crf.
	 *
	 * @param companyId the company ID of this crf
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create user ID of this crf.
	 *
	 * @return the create user ID of this crf
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this crf.
	 *
	 * @param createUserId the create user ID of this crf
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this crf.
	 *
	 * @return the create user uuid of this crf
	 */
	public String getCreateUserUuid();

	/**
	 * Sets the create user uuid of this crf.
	 *
	 * @param createUserUuid the create user uuid of this crf
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this crf.
	 *
	 * @return the create user name of this crf
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this crf.
	 *
	 * @param createUserName the create user name of this crf
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this crf.
	 *
	 * @return the create date of this crf
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this crf.
	 *
	 * @param createDate the create date of this crf
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this crf.
	 *
	 * @return the modified date of this crf
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this crf.
	 *
	 * @param modifiedDate the modified date of this crf
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this crf.
	 *
	 * @return the status of this crf
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this crf.
	 *
	 * @param status the status of this crf
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this crf.
	 *
	 * @return the status by user ID of this crf
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this crf.
	 *
	 * @param statusByUserId the status by user ID of this crf
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this crf.
	 *
	 * @return the status by user uuid of this crf
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this crf.
	 *
	 * @param statusByUserUuid the status by user uuid of this crf
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this crf.
	 *
	 * @return the status by user name of this crf
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this crf.
	 *
	 * @param statusByUserName the status by user name of this crf
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this crf.
	 *
	 * @return the status date of this crf
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this crf.
	 *
	 * @param statusDate the status date of this crf
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the datatype ID of this crf.
	 *
	 * @return the datatype ID of this crf
	 */
	public long getDatatypeId();

	/**
	 * Sets the datatype ID of this crf.
	 *
	 * @param datatypeId the datatype ID of this crf
	 */
	public void setDatatypeId(long datatypeId);

	/**
	 * Returns the manager ID of this crf.
	 *
	 * @return the manager ID of this crf
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this crf.
	 *
	 * @param managerId the manager ID of this crf
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the apply date of this crf.
	 *
	 * @return the apply date of this crf
	 */
	public Date getApplyDate();

	/**
	 * Sets the apply date of this crf.
	 *
	 * @param applyDate the apply date of this crf
	 */
	public void setApplyDate(Date applyDate);

	/**
	 * Returns the crf status of this crf.
	 *
	 * @return the crf status of this crf
	 */
	public int getCrfStatus();

	/**
	 * Sets the crf status of this crf.
	 *
	 * @param crfStatus the crf status of this crf
	 */
	public void setCrfStatus(int crfStatus);

	/**
	 * Returns <code>true</code> if this crf is approved.
	 *
	 * @return <code>true</code> if this crf is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this crf is denied.
	 *
	 * @return <code>true</code> if this crf is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this crf is a draft.
	 *
	 * @return <code>true</code> if this crf is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this crf is expired.
	 *
	 * @return <code>true</code> if this crf is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this crf is inactive.
	 *
	 * @return <code>true</code> if this crf is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this crf is incomplete.
	 *
	 * @return <code>true</code> if this crf is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this crf is pending.
	 *
	 * @return <code>true</code> if this crf is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this crf is scheduled.
	 *
	 * @return <code>true</code> if this crf is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}