/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CRFPatient service. Represents a row in the &quot;EC_CRFPatient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.CRFPatientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.CRFPatientImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see CRFPatient
 * @generated
 */
@ProviderType
public interface CRFPatientModel
	extends BaseModel<CRFPatient>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crf patient model instance should use the {@link CRFPatient} interface instead.
	 */

	/**
	 * Returns the primary key of this crf patient.
	 *
	 * @return the primary key of this crf patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crf patient.
	 *
	 * @param primaryKey the primary key of this crf patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this crf patient.
	 *
	 * @return the mvcc version of this crf patient
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this crf patient.
	 *
	 * @param mvccVersion the mvcc version of this crf patient
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this crf patient.
	 *
	 * @return the uuid of this crf patient
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this crf patient.
	 *
	 * @param uuid the uuid of this crf patient
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the crf patient ID of this crf patient.
	 *
	 * @return the crf patient ID of this crf patient
	 */
	public long getCrfPatientId();

	/**
	 * Sets the crf patient ID of this crf patient.
	 *
	 * @param crfPatientId the crf patient ID of this crf patient
	 */
	public void setCrfPatientId(long crfPatientId);

	/**
	 * Returns the group ID of this crf patient.
	 *
	 * @return the group ID of this crf patient
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this crf patient.
	 *
	 * @param groupId the group ID of this crf patient
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this crf patient.
	 *
	 * @return the company ID of this crf patient
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this crf patient.
	 *
	 * @param companyId the company ID of this crf patient
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create user ID of this crf patient.
	 *
	 * @return the create user ID of this crf patient
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this crf patient.
	 *
	 * @param createUserId the create user ID of this crf patient
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this crf patient.
	 *
	 * @return the create user uuid of this crf patient
	 */
	public String getCreateUserUuid();

	/**
	 * Sets the create user uuid of this crf patient.
	 *
	 * @param createUserUuid the create user uuid of this crf patient
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this crf patient.
	 *
	 * @return the create user name of this crf patient
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this crf patient.
	 *
	 * @param createUserName the create user name of this crf patient
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this crf patient.
	 *
	 * @return the create date of this crf patient
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this crf patient.
	 *
	 * @param createDate the create date of this crf patient
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this crf patient.
	 *
	 * @return the modified date of this crf patient
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this crf patient.
	 *
	 * @param modifiedDate the modified date of this crf patient
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the crf ID of this crf patient.
	 *
	 * @return the crf ID of this crf patient
	 */
	public long getCrfId();

	/**
	 * Sets the crf ID of this crf patient.
	 *
	 * @param crfId the crf ID of this crf patient
	 */
	public void setCrfId(long crfId);

	/**
	 * Returns the patient ID of this crf patient.
	 *
	 * @return the patient ID of this crf patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this crf patient.
	 *
	 * @param patientId the patient ID of this crf patient
	 */
	public void setPatientId(long patientId);

}