/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CRFSearchLog service. Represents a row in the &quot;EC_CRFSearchLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.CRFSearchLogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.CRFSearchLogImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see CRFSearchLog
 * @generated
 */
@ProviderType
public interface CRFSearchLogModel
	extends BaseModel<CRFSearchLog>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crf search log model instance should use the {@link CRFSearchLog} interface instead.
	 */

	/**
	 * Returns the primary key of this crf search log.
	 *
	 * @return the primary key of this crf search log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crf search log.
	 *
	 * @param primaryKey the primary key of this crf search log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this crf search log.
	 *
	 * @return the mvcc version of this crf search log
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this crf search log.
	 *
	 * @param mvccVersion the mvcc version of this crf search log
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this crf search log.
	 *
	 * @return the uuid of this crf search log
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this crf search log.
	 *
	 * @param uuid the uuid of this crf search log
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the search log ID of this crf search log.
	 *
	 * @return the search log ID of this crf search log
	 */
	public long getSearchLogId();

	/**
	 * Sets the search log ID of this crf search log.
	 *
	 * @param searchLogId the search log ID of this crf search log
	 */
	public void setSearchLogId(long searchLogId);

	/**
	 * Returns the group ID of this crf search log.
	 *
	 * @return the group ID of this crf search log
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this crf search log.
	 *
	 * @param groupId the group ID of this crf search log
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this crf search log.
	 *
	 * @return the company ID of this crf search log
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this crf search log.
	 *
	 * @param companyId the company ID of this crf search log
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this crf search log.
	 *
	 * @return the user ID of this crf search log
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this crf search log.
	 *
	 * @param userId the user ID of this crf search log
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this crf search log.
	 *
	 * @return the user uuid of this crf search log
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this crf search log.
	 *
	 * @param userUuid the user uuid of this crf search log
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this crf search log.
	 *
	 * @return the user name of this crf search log
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this crf search log.
	 *
	 * @param userName the user name of this crf search log
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this crf search log.
	 *
	 * @return the create date of this crf search log
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this crf search log.
	 *
	 * @param createDate the create date of this crf search log
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this crf search log.
	 *
	 * @return the modified date of this crf search log
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this crf search log.
	 *
	 * @param modifiedDate the modified date of this crf search log
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the search log of this crf search log.
	 *
	 * @return the search log of this crf search log
	 */
	@AutoEscape
	public String getSearchLog();

	/**
	 * Sets the search log of this crf search log.
	 *
	 * @param searchLog the search log of this crf search log
	 */
	public void setSearchLog(String searchLog);

}