/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CRFSubject service. Represents a row in the &quot;EC_CRFSubject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.CRFSubjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.CRFSubjectImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see CRFSubject
 * @generated
 */
@ProviderType
public interface CRFSubjectModel
	extends BaseModel<CRFSubject>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crf subject model instance should use the {@link CRFSubject} interface instead.
	 */

	/**
	 * Returns the primary key of this crf subject.
	 *
	 * @return the primary key of this crf subject
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crf subject.
	 *
	 * @param primaryKey the primary key of this crf subject
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this crf subject.
	 *
	 * @return the mvcc version of this crf subject
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this crf subject.
	 *
	 * @param mvccVersion the mvcc version of this crf subject
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this crf subject.
	 *
	 * @return the uuid of this crf subject
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this crf subject.
	 *
	 * @param uuid the uuid of this crf subject
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the crf subject ID of this crf subject.
	 *
	 * @return the crf subject ID of this crf subject
	 */
	public long getCrfSubjectId();

	/**
	 * Sets the crf subject ID of this crf subject.
	 *
	 * @param crfSubjectId the crf subject ID of this crf subject
	 */
	public void setCrfSubjectId(long crfSubjectId);

	/**
	 * Returns the group ID of this crf subject.
	 *
	 * @return the group ID of this crf subject
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this crf subject.
	 *
	 * @param groupId the group ID of this crf subject
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this crf subject.
	 *
	 * @return the company ID of this crf subject
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this crf subject.
	 *
	 * @param companyId the company ID of this crf subject
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this crf subject.
	 *
	 * @return the user ID of this crf subject
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this crf subject.
	 *
	 * @param userId the user ID of this crf subject
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this crf subject.
	 *
	 * @return the user uuid of this crf subject
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this crf subject.
	 *
	 * @param userUuid the user uuid of this crf subject
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this crf subject.
	 *
	 * @return the user name of this crf subject
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this crf subject.
	 *
	 * @param userName the user name of this crf subject
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this crf subject.
	 *
	 * @return the create date of this crf subject
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this crf subject.
	 *
	 * @param createDate the create date of this crf subject
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this crf subject.
	 *
	 * @return the modified date of this crf subject
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this crf subject.
	 *
	 * @param modifiedDate the modified date of this crf subject
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the crf ID of this crf subject.
	 *
	 * @return the crf ID of this crf subject
	 */
	public long getCrfId();

	/**
	 * Sets the crf ID of this crf subject.
	 *
	 * @param crfId the crf ID of this crf subject
	 */
	public void setCrfId(long crfId);

	/**
	 * Returns the subject ID of this crf subject.
	 *
	 * @return the subject ID of this crf subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this crf subject.
	 *
	 * @param subjectId the subject ID of this crf subject
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the participation status of this crf subject.
	 *
	 * @return the participation status of this crf subject
	 */
	public int getParticipationStatus();

	/**
	 * Sets the participation status of this crf subject.
	 *
	 * @param participationStatus the participation status of this crf subject
	 */
	public void setParticipationStatus(int participationStatus);

	/**
	 * Returns the participation start date of this crf subject.
	 *
	 * @return the participation start date of this crf subject
	 */
	public Date getParticipationStartDate();

	/**
	 * Sets the participation start date of this crf subject.
	 *
	 * @param participationStartDate the participation start date of this crf subject
	 */
	public void setParticipationStartDate(Date participationStartDate);

	/**
	 * Returns the update lock of this crf subject.
	 *
	 * @return the update lock of this crf subject
	 */
	public boolean getUpdateLock();

	/**
	 * Returns <code>true</code> if this crf subject is update lock.
	 *
	 * @return <code>true</code> if this crf subject is update lock; <code>false</code> otherwise
	 */
	public boolean isUpdateLock();

	/**
	 * Sets whether this crf subject is update lock.
	 *
	 * @param updateLock the update lock of this crf subject
	 */
	public void setUpdateLock(boolean updateLock);

}