/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ExperimentalGroup service. Represents a row in the &quot;EC_ExperimentalGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.ExperimentalGroupModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.ExperimentalGroupImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see ExperimentalGroup
 * @generated
 */
@ProviderType
public interface ExperimentalGroupModel
	extends BaseModel<ExperimentalGroup>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a experimental group model instance should use the {@link ExperimentalGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this experimental group.
	 *
	 * @return the primary key of this experimental group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this experimental group.
	 *
	 * @param primaryKey the primary key of this experimental group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this experimental group.
	 *
	 * @return the mvcc version of this experimental group
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this experimental group.
	 *
	 * @param mvccVersion the mvcc version of this experimental group
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this experimental group.
	 *
	 * @return the uuid of this experimental group
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this experimental group.
	 *
	 * @param uuid the uuid of this experimental group
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the experimental group ID of this experimental group.
	 *
	 * @return the experimental group ID of this experimental group
	 */
	public long getExperimentalGroupId();

	/**
	 * Sets the experimental group ID of this experimental group.
	 *
	 * @param experimentalGroupId the experimental group ID of this experimental group
	 */
	public void setExperimentalGroupId(long experimentalGroupId);

	/**
	 * Returns the company ID of this experimental group.
	 *
	 * @return the company ID of this experimental group
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this experimental group.
	 *
	 * @param companyId the company ID of this experimental group
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this experimental group.
	 *
	 * @return the group ID of this experimental group
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this experimental group.
	 *
	 * @param groupId the group ID of this experimental group
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this experimental group.
	 *
	 * @return the user ID of this experimental group
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this experimental group.
	 *
	 * @param userId the user ID of this experimental group
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this experimental group.
	 *
	 * @return the user uuid of this experimental group
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this experimental group.
	 *
	 * @param userUuid the user uuid of this experimental group
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this experimental group.
	 *
	 * @return the user name of this experimental group
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this experimental group.
	 *
	 * @param userName the user name of this experimental group
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this experimental group.
	 *
	 * @return the create date of this experimental group
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this experimental group.
	 *
	 * @param createDate the create date of this experimental group
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this experimental group.
	 *
	 * @return the modified date of this experimental group
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this experimental group.
	 *
	 * @param modifiedDate the modified date of this experimental group
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this experimental group.
	 *
	 * @return the status of this experimental group
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this experimental group.
	 *
	 * @param status the status of this experimental group
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this experimental group.
	 *
	 * @return the status by user ID of this experimental group
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this experimental group.
	 *
	 * @param statusByUserId the status by user ID of this experimental group
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this experimental group.
	 *
	 * @return the status by user uuid of this experimental group
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this experimental group.
	 *
	 * @param statusByUserUuid the status by user uuid of this experimental group
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this experimental group.
	 *
	 * @return the status by user name of this experimental group
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this experimental group.
	 *
	 * @param statusByUserName the status by user name of this experimental group
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this experimental group.
	 *
	 * @return the status date of this experimental group
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this experimental group.
	 *
	 * @param statusDate the status date of this experimental group
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this experimental group.
	 *
	 * @return the name of this experimental group
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this experimental group.
	 *
	 * @param name the name of this experimental group
	 */
	public void setName(String name);

	/**
	 * Returns the abbr of this experimental group.
	 *
	 * @return the abbr of this experimental group
	 */
	@AutoEscape
	public String getAbbr();

	/**
	 * Sets the abbr of this experimental group.
	 *
	 * @param abbr the abbr of this experimental group
	 */
	public void setAbbr(String abbr);

	/**
	 * Returns the description of this experimental group.
	 *
	 * @return the description of this experimental group
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this experimental group.
	 *
	 * @param description the description of this experimental group
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this experimental group.
	 *
	 * @return the type of this experimental group
	 */
	public int getType();

	/**
	 * Sets the type of this experimental group.
	 *
	 * @param type the type of this experimental group
	 */
	public void setType(int type);

	/**
	 * Returns <code>true</code> if this experimental group is approved.
	 *
	 * @return <code>true</code> if this experimental group is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this experimental group is denied.
	 *
	 * @return <code>true</code> if this experimental group is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this experimental group is a draft.
	 *
	 * @return <code>true</code> if this experimental group is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this experimental group is expired.
	 *
	 * @return <code>true</code> if this experimental group is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this experimental group is inactive.
	 *
	 * @return <code>true</code> if this experimental group is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this experimental group is incomplete.
	 *
	 * @return <code>true</code> if this experimental group is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this experimental group is pending.
	 *
	 * @return <code>true</code> if this experimental group is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this experimental group is scheduled.
	 *
	 * @return <code>true</code> if this experimental group is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}