/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LinkCRF service. Represents a row in the &quot;EC_LinkCRF&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.LinkCRFModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.LinkCRFImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see LinkCRF
 * @generated
 */
@ProviderType
public interface LinkCRFModel
	extends BaseModel<LinkCRF>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a link crf model instance should use the {@link LinkCRF} interface instead.
	 */

	/**
	 * Returns the primary key of this link crf.
	 *
	 * @return the primary key of this link crf
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this link crf.
	 *
	 * @param primaryKey the primary key of this link crf
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this link crf.
	 *
	 * @return the mvcc version of this link crf
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this link crf.
	 *
	 * @param mvccVersion the mvcc version of this link crf
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this link crf.
	 *
	 * @return the uuid of this link crf
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this link crf.
	 *
	 * @param uuid the uuid of this link crf
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the link ID of this link crf.
	 *
	 * @return the link ID of this link crf
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this link crf.
	 *
	 * @param linkId the link ID of this link crf
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the group ID of this link crf.
	 *
	 * @return the group ID of this link crf
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this link crf.
	 *
	 * @param groupId the group ID of this link crf
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this link crf.
	 *
	 * @return the company ID of this link crf
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this link crf.
	 *
	 * @param companyId the company ID of this link crf
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this link crf.
	 *
	 * @return the user ID of this link crf
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this link crf.
	 *
	 * @param userId the user ID of this link crf
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this link crf.
	 *
	 * @return the user uuid of this link crf
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this link crf.
	 *
	 * @param userUuid the user uuid of this link crf
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this link crf.
	 *
	 * @return the user name of this link crf
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this link crf.
	 *
	 * @param userName the user name of this link crf
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this link crf.
	 *
	 * @return the create date of this link crf
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this link crf.
	 *
	 * @param createDate the create date of this link crf
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this link crf.
	 *
	 * @return the modified date of this link crf
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this link crf.
	 *
	 * @param modifiedDate the modified date of this link crf
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject ID of this link crf.
	 *
	 * @return the subject ID of this link crf
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this link crf.
	 *
	 * @param subjectId the subject ID of this link crf
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the crf ID of this link crf.
	 *
	 * @return the crf ID of this link crf
	 */
	public long getCrfId();

	/**
	 * Sets the crf ID of this link crf.
	 *
	 * @param crfId the crf ID of this link crf
	 */
	public void setCrfId(long crfId);

	/**
	 * Returns the structured data ID of this link crf.
	 *
	 * @return the structured data ID of this link crf
	 */
	public long getStructuredDataId();

	/**
	 * Sets the structured data ID of this link crf.
	 *
	 * @param structuredDataId the structured data ID of this link crf
	 */
	public void setStructuredDataId(long structuredDataId);

}