/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;EC_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.PatientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.PatientImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see Patient
 * @generated
 */
@ProviderType
public interface PatientModel
	extends BaseModel<Patient>, MVCCModel, ShardedModel, StagedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
	 */

	/**
	 * Returns the primary key of this patient.
	 *
	 * @return the primary key of this patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient.
	 *
	 * @param primaryKey the primary key of this patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this patient.
	 *
	 * @return the mvcc version of this patient
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this patient.
	 *
	 * @param mvccVersion the mvcc version of this patient
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this patient.
	 *
	 * @return the uuid of this patient
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this patient.
	 *
	 * @param uuid the uuid of this patient
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the patient ID of this patient.
	 *
	 * @return the patient ID of this patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this patient.
	 *
	 * @param patientId the patient ID of this patient
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the group ID of this patient.
	 *
	 * @return the group ID of this patient
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this patient.
	 *
	 * @param groupId the group ID of this patient
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this patient.
	 *
	 * @return the company ID of this patient
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this patient.
	 *
	 * @param companyId the company ID of this patient
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create user ID of this patient.
	 *
	 * @return the create user ID of this patient
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this patient.
	 *
	 * @param createUserId the create user ID of this patient
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this patient.
	 *
	 * @return the create user uuid of this patient
	 */
	public String getCreateUserUuid();

	/**
	 * Sets the create user uuid of this patient.
	 *
	 * @param createUserUuid the create user uuid of this patient
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create user name of this patient.
	 *
	 * @return the create user name of this patient
	 */
	@AutoEscape
	public String getCreateUserName();

	/**
	 * Sets the create user name of this patient.
	 *
	 * @param createUserName the create user name of this patient
	 */
	public void setCreateUserName(String createUserName);

	/**
	 * Returns the create date of this patient.
	 *
	 * @return the create date of this patient
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this patient.
	 *
	 * @param createDate the create date of this patient
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this patient.
	 *
	 * @return the modified date of this patient
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this patient.
	 *
	 * @param modifiedDate the modified date of this patient
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this patient.
	 *
	 * @return the status of this patient
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this patient.
	 *
	 * @param status the status of this patient
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this patient.
	 *
	 * @return the status by user ID of this patient
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this patient.
	 *
	 * @param statusByUserId the status by user ID of this patient
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this patient.
	 *
	 * @return the status by user uuid of this patient
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this patient.
	 *
	 * @param statusByUserUuid the status by user uuid of this patient
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this patient.
	 *
	 * @return the status by user name of this patient
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this patient.
	 *
	 * @param statusByUserName the status by user name of this patient
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this patient.
	 *
	 * @return the status date of this patient
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this patient.
	 *
	 * @param statusDate the status date of this patient
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this patient.
	 *
	 * @return the name of this patient
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patient.
	 *
	 * @param name the name of this patient
	 */
	public void setName(String name);

	/**
	 * Returns the birth of this patient.
	 *
	 * @return the birth of this patient
	 */
	public Date getBirth();

	/**
	 * Sets the birth of this patient.
	 *
	 * @param birth the birth of this patient
	 */
	public void setBirth(Date birth);

	/**
	 * Returns the phone of this patient.
	 *
	 * @return the phone of this patient
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this patient.
	 *
	 * @param phone the phone of this patient
	 */
	public void setPhone(String phone);

	/**
	 * Returns the position of this patient.
	 *
	 * @return the position of this patient
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this patient.
	 *
	 * @param position the position of this patient
	 */
	public void setPosition(String position);

	/**
	 * Returns the gender of this patient.
	 *
	 * @return the gender of this patient
	 */
	public int getGender();

	/**
	 * Sets the gender of this patient.
	 *
	 * @param gender the gender of this patient
	 */
	public void setGender(int gender);

	/**
	 * Returns the consent date of this patient.
	 *
	 * @return the consent date of this patient
	 */
	public Date getConsentDate();

	/**
	 * Sets the consent date of this patient.
	 *
	 * @param consentDate the consent date of this patient
	 */
	public void setConsentDate(Date consentDate);

	/**
	 * Returns the participation start date of this patient.
	 *
	 * @return the participation start date of this patient
	 */
	public Date getParticipationStartDate();

	/**
	 * Sets the participation start date of this patient.
	 *
	 * @param participationStartDate the participation start date of this patient
	 */
	public void setParticipationStartDate(Date participationStartDate);

	/**
	 * Returns the participation status of this patient.
	 *
	 * @return the participation status of this patient
	 */
	public int getParticipationStatus();

	/**
	 * Sets the participation status of this patient.
	 *
	 * @param participationStatus the participation status of this patient
	 */
	public void setParticipationStatus(int participationStatus);

	/**
	 * Returns the experimental group of this patient.
	 *
	 * @return the experimental group of this patient
	 */
	@AutoEscape
	public String getExperimentalGroup();

	/**
	 * Sets the experimental group of this patient.
	 *
	 * @param experimentalGroup the experimental group of this patient
	 */
	public void setExperimentalGroup(String experimentalGroup);

	/**
	 * Returns the patient user ID of this patient.
	 *
	 * @return the patient user ID of this patient
	 */
	public long getPatientUserId();

	/**
	 * Sets the patient user ID of this patient.
	 *
	 * @param patientUserId the patient user ID of this patient
	 */
	public void setPatientUserId(long patientUserId);

	/**
	 * Returns the patient user uuid of this patient.
	 *
	 * @return the patient user uuid of this patient
	 */
	public String getPatientUserUuid();

	/**
	 * Sets the patient user uuid of this patient.
	 *
	 * @param patientUserUuid the patient user uuid of this patient
	 */
	public void setPatientUserUuid(String patientUserUuid);

	/**
	 * Returns <code>true</code> if this patient is approved.
	 *
	 * @return <code>true</code> if this patient is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this patient is denied.
	 *
	 * @return <code>true</code> if this patient is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this patient is a draft.
	 *
	 * @return <code>true</code> if this patient is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this patient is expired.
	 *
	 * @return <code>true</code> if this patient is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this patient is inactive.
	 *
	 * @return <code>true</code> if this patient is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this patient is incomplete.
	 *
	 * @return <code>true</code> if this patient is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this patient is pending.
	 *
	 * @return <code>true</code> if this patient is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this patient is scheduled.
	 *
	 * @return <code>true</code> if this patient is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}