/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SelfSiteRequest service. Represents a row in the &quot;EC_SelfSiteRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ecrf.user.model.impl.SelfSiteRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ecrf.user.model.impl.SelfSiteRequestImpl</code>.
 * </p>
 *
 * @author Ryu W.C.
 * @see SelfSiteRequest
 * @generated
 */
@ProviderType
public interface SelfSiteRequestModel
	extends BaseModel<SelfSiteRequest>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a self site request model instance should use the {@link SelfSiteRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this self site request.
	 *
	 * @return the primary key of this self site request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this self site request.
	 *
	 * @param primaryKey the primary key of this self site request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this self site request.
	 *
	 * @return the mvcc version of this self site request
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this self site request.
	 *
	 * @param mvccVersion the mvcc version of this self site request
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this self site request.
	 *
	 * @return the uuid of this self site request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this self site request.
	 *
	 * @param uuid the uuid of this self site request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the self site request ID of this self site request.
	 *
	 * @return the self site request ID of this self site request
	 */
	public long getSelfSiteRequestId();

	/**
	 * Sets the self site request ID of this self site request.
	 *
	 * @param selfSiteRequestId the self site request ID of this self site request
	 */
	public void setSelfSiteRequestId(long selfSiteRequestId);

	/**
	 * Returns the group ID of this self site request.
	 *
	 * @return the group ID of this self site request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this self site request.
	 *
	 * @param groupId the group ID of this self site request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this self site request.
	 *
	 * @return the company ID of this self site request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this self site request.
	 *
	 * @param companyId the company ID of this self site request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this self site request.
	 *
	 * @return the user ID of this self site request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this self site request.
	 *
	 * @param userId the user ID of this self site request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this self site request.
	 *
	 * @return the user uuid of this self site request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this self site request.
	 *
	 * @param userUuid the user uuid of this self site request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this self site request.
	 *
	 * @return the user name of this self site request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this self site request.
	 *
	 * @param userName the user name of this self site request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this self site request.
	 *
	 * @return the create date of this self site request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this self site request.
	 *
	 * @param createDate the create date of this self site request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this self site request.
	 *
	 * @return the modified date of this self site request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this self site request.
	 *
	 * @param modifiedDate the modified date of this self site request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email of this self site request.
	 *
	 * @return the email of this self site request
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this self site request.
	 *
	 * @param email the email of this self site request
	 */
	public void setEmail(String email);

	/**
	 * Returns the last name of this self site request.
	 *
	 * @return the last name of this self site request
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this self site request.
	 *
	 * @param lastName the last name of this self site request
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the first name of this self site request.
	 *
	 * @return the first name of this self site request
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this self site request.
	 *
	 * @param firstName the first name of this self site request
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the phone of this self site request.
	 *
	 * @return the phone of this self site request
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this self site request.
	 *
	 * @param phone the phone of this self site request
	 */
	public void setPhone(String phone);

	/**
	 * Returns the project title of this self site request.
	 *
	 * @return the project title of this self site request
	 */
	@AutoEscape
	public String getProjectTitle();

	/**
	 * Sets the project title of this self site request.
	 *
	 * @param projectTitle the project title of this self site request
	 */
	public void setProjectTitle(String projectTitle);

	/**
	 * Returns the project description of this self site request.
	 *
	 * @return the project description of this self site request
	 */
	@AutoEscape
	public String getProjectDescription();

	/**
	 * Sets the project description of this self site request.
	 *
	 * @param projectDescription the project description of this self site request
	 */
	public void setProjectDescription(String projectDescription);

}