/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import ecrf.user.model.ExperimentalGroup;
import ecrf.user.model.ExperimentalGroupModel;
import ecrf.user.model.ExperimentalGroupSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExperimentalGroup service. Represents a row in the &quot;EC_ExperimentalGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExperimentalGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExperimentalGroupImpl}.
 * </p>
 *
 * @author Ryu W.C.
 * @see ExperimentalGroupImpl
 * @generated
 */
@JSON(strict = true)
public class ExperimentalGroupModelImpl
	extends BaseModelImpl<ExperimentalGroup> implements ExperimentalGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a experimental group model instance should use the <code>ExperimentalGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "EC_ExperimentalGroup";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"experimentalGroupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"abbr", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("experimentalGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("abbr", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EC_ExperimentalGroup (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,experimentalGroupId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null,abbr VARCHAR(75) null,description VARCHAR(75) null,type_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table EC_ExperimentalGroup";

	public static final String ORDER_BY_JPQL =
		" ORDER BY experimentalGroup.experimentalGroupId DESC, experimentalGroup.name ASC, experimentalGroup.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EC_ExperimentalGroup.experimentalGroupId DESC, EC_ExperimentalGroup.name ASC, EC_ExperimentalGroup.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXPERIMENTALGROUPID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long NAME_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ExperimentalGroup toModel(ExperimentalGroupSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ExperimentalGroup model = new ExperimentalGroupImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setExperimentalGroupId(soapModel.getExperimentalGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setName(soapModel.getName());
		model.setAbbr(soapModel.getAbbr());
		model.setDescription(soapModel.getDescription());
		model.setType(soapModel.getType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ExperimentalGroup> toModels(
		ExperimentalGroupSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ExperimentalGroup> models = new ArrayList<ExperimentalGroup>(
			soapModels.length);

		for (ExperimentalGroupSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ExperimentalGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _experimentalGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExperimentalGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _experimentalGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExperimentalGroup.class;
	}

	@Override
	public String getModelClassName() {
		return ExperimentalGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExperimentalGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExperimentalGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExperimentalGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ExperimentalGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExperimentalGroup, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExperimentalGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExperimentalGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExperimentalGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExperimentalGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ExperimentalGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ExperimentalGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ExperimentalGroup, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ExperimentalGroup, Object>>();
		Map<String, BiConsumer<ExperimentalGroup, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ExperimentalGroup, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", ExperimentalGroup::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ExperimentalGroup, Long>)
				ExperimentalGroup::setMvccVersion);
		attributeGetterFunctions.put("uuid", ExperimentalGroup::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ExperimentalGroup, String>)ExperimentalGroup::setUuid);
		attributeGetterFunctions.put(
			"experimentalGroupId", ExperimentalGroup::getExperimentalGroupId);
		attributeSetterBiConsumers.put(
			"experimentalGroupId",
			(BiConsumer<ExperimentalGroup, Long>)
				ExperimentalGroup::setExperimentalGroupId);
		attributeGetterFunctions.put(
			"companyId", ExperimentalGroup::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ExperimentalGroup, Long>)
				ExperimentalGroup::setCompanyId);
		attributeGetterFunctions.put("groupId", ExperimentalGroup::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ExperimentalGroup, Long>)ExperimentalGroup::setGroupId);
		attributeGetterFunctions.put("userId", ExperimentalGroup::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ExperimentalGroup, Long>)ExperimentalGroup::setUserId);
		attributeGetterFunctions.put(
			"userName", ExperimentalGroup::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ExperimentalGroup, String>)
				ExperimentalGroup::setUserName);
		attributeGetterFunctions.put(
			"createDate", ExperimentalGroup::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ExperimentalGroup, Date>)
				ExperimentalGroup::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ExperimentalGroup::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ExperimentalGroup, Date>)
				ExperimentalGroup::setModifiedDate);
		attributeGetterFunctions.put("status", ExperimentalGroup::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ExperimentalGroup, Integer>)
				ExperimentalGroup::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", ExperimentalGroup::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<ExperimentalGroup, Long>)
				ExperimentalGroup::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", ExperimentalGroup::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<ExperimentalGroup, String>)
				ExperimentalGroup::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", ExperimentalGroup::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<ExperimentalGroup, Date>)
				ExperimentalGroup::setStatusDate);
		attributeGetterFunctions.put("name", ExperimentalGroup::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<ExperimentalGroup, String>)ExperimentalGroup::setName);
		attributeGetterFunctions.put("abbr", ExperimentalGroup::getAbbr);
		attributeSetterBiConsumers.put(
			"abbr",
			(BiConsumer<ExperimentalGroup, String>)ExperimentalGroup::setAbbr);
		attributeGetterFunctions.put(
			"description", ExperimentalGroup::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ExperimentalGroup, String>)
				ExperimentalGroup::setDescription);
		attributeGetterFunctions.put("type", ExperimentalGroup::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<ExperimentalGroup, Integer>)ExperimentalGroup::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getExperimentalGroupId() {
		return _experimentalGroupId;
	}

	@Override
	public void setExperimentalGroupId(long experimentalGroupId) {
		_columnBitmask = -1L;

		if (!_setOriginalExperimentalGroupId) {
			_setOriginalExperimentalGroupId = true;

			_originalExperimentalGroupId = _experimentalGroupId;
		}

		_experimentalGroupId = experimentalGroupId;
	}

	public long getOriginalExperimentalGroupId() {
		return _originalExperimentalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getAbbr() {
		if (_abbr == null) {
			return "";
		}
		else {
			return _abbr;
		}
	}

	@Override
	public void setAbbr(String abbr) {
		_abbr = abbr;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ExperimentalGroup.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ExperimentalGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExperimentalGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExperimentalGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExperimentalGroupImpl experimentalGroupImpl =
			new ExperimentalGroupImpl();

		experimentalGroupImpl.setMvccVersion(getMvccVersion());
		experimentalGroupImpl.setUuid(getUuid());
		experimentalGroupImpl.setExperimentalGroupId(getExperimentalGroupId());
		experimentalGroupImpl.setCompanyId(getCompanyId());
		experimentalGroupImpl.setGroupId(getGroupId());
		experimentalGroupImpl.setUserId(getUserId());
		experimentalGroupImpl.setUserName(getUserName());
		experimentalGroupImpl.setCreateDate(getCreateDate());
		experimentalGroupImpl.setModifiedDate(getModifiedDate());
		experimentalGroupImpl.setStatus(getStatus());
		experimentalGroupImpl.setStatusByUserId(getStatusByUserId());
		experimentalGroupImpl.setStatusByUserName(getStatusByUserName());
		experimentalGroupImpl.setStatusDate(getStatusDate());
		experimentalGroupImpl.setName(getName());
		experimentalGroupImpl.setAbbr(getAbbr());
		experimentalGroupImpl.setDescription(getDescription());
		experimentalGroupImpl.setType(getType());

		experimentalGroupImpl.resetOriginalValues();

		return experimentalGroupImpl;
	}

	@Override
	public int compareTo(ExperimentalGroup experimentalGroup) {
		int value = 0;

		if (getExperimentalGroupId() <
				experimentalGroup.getExperimentalGroupId()) {

			value = -1;
		}
		else if (getExperimentalGroupId() >
					experimentalGroup.getExperimentalGroupId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getName().compareTo(experimentalGroup.getName());

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(
			getCreateDate(), experimentalGroup.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExperimentalGroup)) {
			return false;
		}

		ExperimentalGroup experimentalGroup = (ExperimentalGroup)object;

		long primaryKey = experimentalGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalExperimentalGroupId = _experimentalGroupId;

		_setOriginalExperimentalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_setModifiedDate = false;

		_originalName = _name;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExperimentalGroup> toCacheModel() {
		ExperimentalGroupCacheModel experimentalGroupCacheModel =
			new ExperimentalGroupCacheModel();

		experimentalGroupCacheModel.mvccVersion = getMvccVersion();

		experimentalGroupCacheModel.uuid = getUuid();

		String uuid = experimentalGroupCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			experimentalGroupCacheModel.uuid = null;
		}

		experimentalGroupCacheModel.experimentalGroupId =
			getExperimentalGroupId();

		experimentalGroupCacheModel.companyId = getCompanyId();

		experimentalGroupCacheModel.groupId = getGroupId();

		experimentalGroupCacheModel.userId = getUserId();

		experimentalGroupCacheModel.userName = getUserName();

		String userName = experimentalGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			experimentalGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			experimentalGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			experimentalGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			experimentalGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			experimentalGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		experimentalGroupCacheModel.status = getStatus();

		experimentalGroupCacheModel.statusByUserId = getStatusByUserId();

		experimentalGroupCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = experimentalGroupCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			experimentalGroupCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			experimentalGroupCacheModel.statusDate = statusDate.getTime();
		}
		else {
			experimentalGroupCacheModel.statusDate = Long.MIN_VALUE;
		}

		experimentalGroupCacheModel.name = getName();

		String name = experimentalGroupCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			experimentalGroupCacheModel.name = null;
		}

		experimentalGroupCacheModel.abbr = getAbbr();

		String abbr = experimentalGroupCacheModel.abbr;

		if ((abbr != null) && (abbr.length() == 0)) {
			experimentalGroupCacheModel.abbr = null;
		}

		experimentalGroupCacheModel.description = getDescription();

		String description = experimentalGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			experimentalGroupCacheModel.description = null;
		}

		experimentalGroupCacheModel.type = getType();

		return experimentalGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExperimentalGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExperimentalGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExperimentalGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ExperimentalGroup)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ExperimentalGroup, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ExperimentalGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExperimentalGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ExperimentalGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ExperimentalGroup>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ExperimentalGroup.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _experimentalGroupId;
	private long _originalExperimentalGroupId;
	private boolean _setOriginalExperimentalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _name;
	private String _originalName;
	private String _abbr;
	private String _description;
	private int _type;
	private long _columnBitmask;
	private ExperimentalGroup _escapedModel;

}