/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import ecrf.user.model.Patient;
import ecrf.user.model.PatientModel;
import ecrf.user.model.PatientSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Patient service. Represents a row in the &quot;EC_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatientModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientImpl}.
 * </p>
 *
 * @author Ryu W.C.
 * @see PatientImpl
 * @generated
 */
@JSON(strict = true)
public class PatientModelImpl
	extends BaseModelImpl<Patient> implements PatientModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patient model instance should use the <code>Patient</code> interface instead.
	 */
	public static final String TABLE_NAME = "EC_Patient";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"patientId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"birth", Types.TIMESTAMP}, {"position", Types.VARCHAR},
		{"gender", Types.INTEGER}, {"phone", Types.VARCHAR},
		{"phone2", Types.VARCHAR}, {"serialId", Types.VARCHAR},
		{"hospitalCode", Types.INTEGER}, {"visitDate", Types.TIMESTAMP},
		{"consentDate", Types.TIMESTAMP},
		{"participationStartDate", Types.TIMESTAMP},
		{"participationStatus", Types.INTEGER},
		{"experimentalGroup", Types.VARCHAR}, {"hasCRF", Types.BOOLEAN},
		{"hasCohortStudy", Types.BOOLEAN}, {"hasMRIStudy", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("patientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("position", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phone2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serialId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hospitalCode", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("visitDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("consentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("participationStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("participationStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("experimentalGroup", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hasCRF", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hasCohortStudy", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hasMRIStudy", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EC_Patient (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,patientId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null,birth DATE null,position VARCHAR(75) null,gender INTEGER,phone VARCHAR(75) null,phone2 VARCHAR(75) null,serialId VARCHAR(75) null,hospitalCode INTEGER,visitDate DATE null,consentDate DATE null,participationStartDate DATE null,participationStatus INTEGER,experimentalGroup VARCHAR(75) null,hasCRF BOOLEAN,hasCohortStudy BOOLEAN,hasMRIStudy BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table EC_Patient";

	public static final String ORDER_BY_JPQL =
		" ORDER BY patient.patientId ASC, patient.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EC_Patient.patientId ASC, EC_Patient.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long PATIENTID_COLUMN_BITMASK = 8L;

	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Patient toModel(PatientSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Patient model = new PatientImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setPatientId(soapModel.getPatientId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setName(soapModel.getName());
		model.setBirth(soapModel.getBirth());
		model.setPosition(soapModel.getPosition());
		model.setGender(soapModel.getGender());
		model.setPhone(soapModel.getPhone());
		model.setPhone2(soapModel.getPhone2());
		model.setSerialId(soapModel.getSerialId());
		model.setHospitalCode(soapModel.getHospitalCode());
		model.setVisitDate(soapModel.getVisitDate());
		model.setConsentDate(soapModel.getConsentDate());
		model.setParticipationStartDate(soapModel.getParticipationStartDate());
		model.setParticipationStatus(soapModel.getParticipationStatus());
		model.setExperimentalGroup(soapModel.getExperimentalGroup());
		model.setHasCRF(soapModel.getHasCRF());
		model.setHasCohortStudy(soapModel.getHasCohortStudy());
		model.setHasMRIStudy(soapModel.getHasMRIStudy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Patient> toModels(PatientSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Patient> models = new ArrayList<Patient>(soapModels.length);

		for (PatientSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PatientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patientId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatientId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patientId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Patient.class;
	}

	@Override
	public String getModelClassName() {
		return Patient.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Patient, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Patient, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Patient)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Patient, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Patient, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Patient)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Patient, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Patient, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Patient, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Patient, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Patient, Object>>();
		Map<String, BiConsumer<Patient, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Patient, ?>>();

		attributeGetterFunctions.put("mvccVersion", Patient::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion", (BiConsumer<Patient, Long>)Patient::setMvccVersion);
		attributeGetterFunctions.put("uuid", Patient::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Patient, String>)Patient::setUuid);
		attributeGetterFunctions.put("patientId", Patient::getPatientId);
		attributeSetterBiConsumers.put(
			"patientId", (BiConsumer<Patient, Long>)Patient::setPatientId);
		attributeGetterFunctions.put("companyId", Patient::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Patient, Long>)Patient::setCompanyId);
		attributeGetterFunctions.put("groupId", Patient::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Patient, Long>)Patient::setGroupId);
		attributeGetterFunctions.put("userId", Patient::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Patient, Long>)Patient::setUserId);
		attributeGetterFunctions.put("userName", Patient::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Patient, String>)Patient::setUserName);
		attributeGetterFunctions.put("createDate", Patient::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Patient, Date>)Patient::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Patient::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Patient, Date>)Patient::setModifiedDate);
		attributeGetterFunctions.put("status", Patient::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Patient, Integer>)Patient::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Patient::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Patient, Long>)Patient::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Patient::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Patient, String>)Patient::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Patient::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Patient, Date>)Patient::setStatusDate);
		attributeGetterFunctions.put("name", Patient::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Patient, String>)Patient::setName);
		attributeGetterFunctions.put("birth", Patient::getBirth);
		attributeSetterBiConsumers.put(
			"birth", (BiConsumer<Patient, Date>)Patient::setBirth);
		attributeGetterFunctions.put("position", Patient::getPosition);
		attributeSetterBiConsumers.put(
			"position", (BiConsumer<Patient, String>)Patient::setPosition);
		attributeGetterFunctions.put("gender", Patient::getGender);
		attributeSetterBiConsumers.put(
			"gender", (BiConsumer<Patient, Integer>)Patient::setGender);
		attributeGetterFunctions.put("phone", Patient::getPhone);
		attributeSetterBiConsumers.put(
			"phone", (BiConsumer<Patient, String>)Patient::setPhone);
		attributeGetterFunctions.put("phone2", Patient::getPhone2);
		attributeSetterBiConsumers.put(
			"phone2", (BiConsumer<Patient, String>)Patient::setPhone2);
		attributeGetterFunctions.put("serialId", Patient::getSerialId);
		attributeSetterBiConsumers.put(
			"serialId", (BiConsumer<Patient, String>)Patient::setSerialId);
		attributeGetterFunctions.put("hospitalCode", Patient::getHospitalCode);
		attributeSetterBiConsumers.put(
			"hospitalCode",
			(BiConsumer<Patient, Integer>)Patient::setHospitalCode);
		attributeGetterFunctions.put("visitDate", Patient::getVisitDate);
		attributeSetterBiConsumers.put(
			"visitDate", (BiConsumer<Patient, Date>)Patient::setVisitDate);
		attributeGetterFunctions.put("consentDate", Patient::getConsentDate);
		attributeSetterBiConsumers.put(
			"consentDate", (BiConsumer<Patient, Date>)Patient::setConsentDate);
		attributeGetterFunctions.put(
			"participationStartDate", Patient::getParticipationStartDate);
		attributeSetterBiConsumers.put(
			"participationStartDate",
			(BiConsumer<Patient, Date>)Patient::setParticipationStartDate);
		attributeGetterFunctions.put(
			"participationStatus", Patient::getParticipationStatus);
		attributeSetterBiConsumers.put(
			"participationStatus",
			(BiConsumer<Patient, Integer>)Patient::setParticipationStatus);
		attributeGetterFunctions.put(
			"experimentalGroup", Patient::getExperimentalGroup);
		attributeSetterBiConsumers.put(
			"experimentalGroup",
			(BiConsumer<Patient, String>)Patient::setExperimentalGroup);
		attributeGetterFunctions.put("hasCRF", Patient::getHasCRF);
		attributeSetterBiConsumers.put(
			"hasCRF", (BiConsumer<Patient, Boolean>)Patient::setHasCRF);
		attributeGetterFunctions.put(
			"hasCohortStudy", Patient::getHasCohortStudy);
		attributeSetterBiConsumers.put(
			"hasCohortStudy",
			(BiConsumer<Patient, Boolean>)Patient::setHasCohortStudy);
		attributeGetterFunctions.put("hasMRIStudy", Patient::getHasMRIStudy);
		attributeSetterBiConsumers.put(
			"hasMRIStudy",
			(BiConsumer<Patient, Boolean>)Patient::setHasMRIStudy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPatientId() {
		return _patientId;
	}

	@Override
	public void setPatientId(long patientId) {
		_columnBitmask = -1L;

		_patientId = patientId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public Date getBirth() {
		return _birth;
	}

	@Override
	public void setBirth(Date birth) {
		_birth = birth;
	}

	@JSON
	@Override
	public String getPosition() {
		if (_position == null) {
			return "";
		}
		else {
			return _position;
		}
	}

	@Override
	public void setPosition(String position) {
		_position = position;
	}

	@JSON
	@Override
	public int getGender() {
		return _gender;
	}

	@Override
	public void setGender(int gender) {
		_gender = gender;
	}

	@JSON
	@Override
	public String getPhone() {
		if (_phone == null) {
			return "";
		}
		else {
			return _phone;
		}
	}

	@Override
	public void setPhone(String phone) {
		_phone = phone;
	}

	@JSON
	@Override
	public String getPhone2() {
		if (_phone2 == null) {
			return "";
		}
		else {
			return _phone2;
		}
	}

	@Override
	public void setPhone2(String phone2) {
		_phone2 = phone2;
	}

	@JSON
	@Override
	public String getSerialId() {
		if (_serialId == null) {
			return "";
		}
		else {
			return _serialId;
		}
	}

	@Override
	public void setSerialId(String serialId) {
		_serialId = serialId;
	}

	@JSON
	@Override
	public int getHospitalCode() {
		return _hospitalCode;
	}

	@Override
	public void setHospitalCode(int hospitalCode) {
		_hospitalCode = hospitalCode;
	}

	@JSON
	@Override
	public Date getVisitDate() {
		return _visitDate;
	}

	@Override
	public void setVisitDate(Date visitDate) {
		_visitDate = visitDate;
	}

	@JSON
	@Override
	public Date getConsentDate() {
		return _consentDate;
	}

	@Override
	public void setConsentDate(Date consentDate) {
		_consentDate = consentDate;
	}

	@JSON
	@Override
	public Date getParticipationStartDate() {
		return _participationStartDate;
	}

	@Override
	public void setParticipationStartDate(Date participationStartDate) {
		_participationStartDate = participationStartDate;
	}

	@JSON
	@Override
	public int getParticipationStatus() {
		return _participationStatus;
	}

	@Override
	public void setParticipationStatus(int participationStatus) {
		_participationStatus = participationStatus;
	}

	@JSON
	@Override
	public String getExperimentalGroup() {
		if (_experimentalGroup == null) {
			return "";
		}
		else {
			return _experimentalGroup;
		}
	}

	@Override
	public void setExperimentalGroup(String experimentalGroup) {
		_experimentalGroup = experimentalGroup;
	}

	@JSON
	@Override
	public Boolean getHasCRF() {
		return _hasCRF;
	}

	@Override
	public void setHasCRF(Boolean hasCRF) {
		_hasCRF = hasCRF;
	}

	@JSON
	@Override
	public Boolean getHasCohortStudy() {
		return _hasCohortStudy;
	}

	@Override
	public void setHasCohortStudy(Boolean hasCohortStudy) {
		_hasCohortStudy = hasCohortStudy;
	}

	@JSON
	@Override
	public Boolean getHasMRIStudy() {
		return _hasMRIStudy;
	}

	@Override
	public void setHasMRIStudy(Boolean hasMRIStudy) {
		_hasMRIStudy = hasMRIStudy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Patient.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Patient.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Patient toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Patient>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatientImpl patientImpl = new PatientImpl();

		patientImpl.setMvccVersion(getMvccVersion());
		patientImpl.setUuid(getUuid());
		patientImpl.setPatientId(getPatientId());
		patientImpl.setCompanyId(getCompanyId());
		patientImpl.setGroupId(getGroupId());
		patientImpl.setUserId(getUserId());
		patientImpl.setUserName(getUserName());
		patientImpl.setCreateDate(getCreateDate());
		patientImpl.setModifiedDate(getModifiedDate());
		patientImpl.setStatus(getStatus());
		patientImpl.setStatusByUserId(getStatusByUserId());
		patientImpl.setStatusByUserName(getStatusByUserName());
		patientImpl.setStatusDate(getStatusDate());
		patientImpl.setName(getName());
		patientImpl.setBirth(getBirth());
		patientImpl.setPosition(getPosition());
		patientImpl.setGender(getGender());
		patientImpl.setPhone(getPhone());
		patientImpl.setPhone2(getPhone2());
		patientImpl.setSerialId(getSerialId());
		patientImpl.setHospitalCode(getHospitalCode());
		patientImpl.setVisitDate(getVisitDate());
		patientImpl.setConsentDate(getConsentDate());
		patientImpl.setParticipationStartDate(getParticipationStartDate());
		patientImpl.setParticipationStatus(getParticipationStatus());
		patientImpl.setExperimentalGroup(getExperimentalGroup());
		patientImpl.setHasCRF(getHasCRF());
		patientImpl.setHasCohortStudy(getHasCohortStudy());
		patientImpl.setHasMRIStudy(getHasMRIStudy());

		patientImpl.resetOriginalValues();

		return patientImpl;
	}

	@Override
	public int compareTo(Patient patient) {
		int value = 0;

		if (getPatientId() < patient.getPatientId()) {
			value = -1;
		}
		else if (getPatientId() > patient.getPatientId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(), patient.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Patient)) {
			return false;
		}

		Patient patient = (Patient)object;

		long primaryKey = patient.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Patient> toCacheModel() {
		PatientCacheModel patientCacheModel = new PatientCacheModel();

		patientCacheModel.mvccVersion = getMvccVersion();

		patientCacheModel.uuid = getUuid();

		String uuid = patientCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			patientCacheModel.uuid = null;
		}

		patientCacheModel.patientId = getPatientId();

		patientCacheModel.companyId = getCompanyId();

		patientCacheModel.groupId = getGroupId();

		patientCacheModel.userId = getUserId();

		patientCacheModel.userName = getUserName();

		String userName = patientCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			patientCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			patientCacheModel.createDate = createDate.getTime();
		}
		else {
			patientCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patientCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			patientCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patientCacheModel.status = getStatus();

		patientCacheModel.statusByUserId = getStatusByUserId();

		patientCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = patientCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			patientCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			patientCacheModel.statusDate = statusDate.getTime();
		}
		else {
			patientCacheModel.statusDate = Long.MIN_VALUE;
		}

		patientCacheModel.name = getName();

		String name = patientCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			patientCacheModel.name = null;
		}

		Date birth = getBirth();

		if (birth != null) {
			patientCacheModel.birth = birth.getTime();
		}
		else {
			patientCacheModel.birth = Long.MIN_VALUE;
		}

		patientCacheModel.position = getPosition();

		String position = patientCacheModel.position;

		if ((position != null) && (position.length() == 0)) {
			patientCacheModel.position = null;
		}

		patientCacheModel.gender = getGender();

		patientCacheModel.phone = getPhone();

		String phone = patientCacheModel.phone;

		if ((phone != null) && (phone.length() == 0)) {
			patientCacheModel.phone = null;
		}

		patientCacheModel.phone2 = getPhone2();

		String phone2 = patientCacheModel.phone2;

		if ((phone2 != null) && (phone2.length() == 0)) {
			patientCacheModel.phone2 = null;
		}

		patientCacheModel.serialId = getSerialId();

		String serialId = patientCacheModel.serialId;

		if ((serialId != null) && (serialId.length() == 0)) {
			patientCacheModel.serialId = null;
		}

		patientCacheModel.hospitalCode = getHospitalCode();

		Date visitDate = getVisitDate();

		if (visitDate != null) {
			patientCacheModel.visitDate = visitDate.getTime();
		}
		else {
			patientCacheModel.visitDate = Long.MIN_VALUE;
		}

		Date consentDate = getConsentDate();

		if (consentDate != null) {
			patientCacheModel.consentDate = consentDate.getTime();
		}
		else {
			patientCacheModel.consentDate = Long.MIN_VALUE;
		}

		Date participationStartDate = getParticipationStartDate();

		if (participationStartDate != null) {
			patientCacheModel.participationStartDate =
				participationStartDate.getTime();
		}
		else {
			patientCacheModel.participationStartDate = Long.MIN_VALUE;
		}

		patientCacheModel.participationStatus = getParticipationStatus();

		patientCacheModel.experimentalGroup = getExperimentalGroup();

		String experimentalGroup = patientCacheModel.experimentalGroup;

		if ((experimentalGroup != null) && (experimentalGroup.length() == 0)) {
			patientCacheModel.experimentalGroup = null;
		}

		Boolean hasCRF = getHasCRF();

		if (hasCRF != null) {
			patientCacheModel.hasCRF = hasCRF;
		}

		Boolean hasCohortStudy = getHasCohortStudy();

		if (hasCohortStudy != null) {
			patientCacheModel.hasCohortStudy = hasCohortStudy;
		}

		Boolean hasMRIStudy = getHasMRIStudy();

		if (hasMRIStudy != null) {
			patientCacheModel.hasMRIStudy = hasMRIStudy;
		}

		return patientCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Patient, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Patient, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Patient)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Patient, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Patient, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Patient)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Patient>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Patient.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _patientId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _name;
	private Date _birth;
	private String _position;
	private int _gender;
	private String _phone;
	private String _phone2;
	private String _serialId;
	private int _hospitalCode;
	private Date _visitDate;
	private Date _consentDate;
	private Date _participationStartDate;
	private int _participationStatus;
	private String _experimentalGroup;
	private Boolean _hasCRF;
	private Boolean _hasCohortStudy;
	private Boolean _hasMRIStudy;
	private long _columnBitmask;
	private Patient _escapedModel;

}