/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ecrf.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import ecrf.user.model.SelfSiteRequest;
import ecrf.user.model.SelfSiteRequestModel;
import ecrf.user.model.SelfSiteRequestSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SelfSiteRequest service. Represents a row in the &quot;EC_SelfSiteRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SelfSiteRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SelfSiteRequestImpl}.
 * </p>
 *
 * @author Ryu W.C.
 * @see SelfSiteRequestImpl
 * @generated
 */
@JSON(strict = true)
public class SelfSiteRequestModelImpl
	extends BaseModelImpl<SelfSiteRequest> implements SelfSiteRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a self site request model instance should use the <code>SelfSiteRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "EC_SelfSiteRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"selfSiteRequestId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"email", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"firstName", Types.VARCHAR},
		{"phone", Types.VARCHAR}, {"projectTitle", Types.VARCHAR},
		{"projectDescription", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("selfSiteRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectDescription", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EC_SelfSiteRequest (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,selfSiteRequestId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,email VARCHAR(75) null,lastName VARCHAR(75) null,firstName VARCHAR(75) null,phone VARCHAR(75) null,projectTitle VARCHAR(75) null,projectDescription TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table EC_SelfSiteRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY selfSiteRequest.selfSiteRequestId DESC, selfSiteRequest.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EC_SelfSiteRequest.selfSiteRequestId DESC, EC_SelfSiteRequest.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long SELFSITEREQUESTID_COLUMN_BITMASK = 8L;

	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SelfSiteRequest toModel(SelfSiteRequestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SelfSiteRequest model = new SelfSiteRequestImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setSelfSiteRequestId(soapModel.getSelfSiteRequestId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEmail(soapModel.getEmail());
		model.setLastName(soapModel.getLastName());
		model.setFirstName(soapModel.getFirstName());
		model.setPhone(soapModel.getPhone());
		model.setProjectTitle(soapModel.getProjectTitle());
		model.setProjectDescription(soapModel.getProjectDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SelfSiteRequest> toModels(
		SelfSiteRequestSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SelfSiteRequest> models = new ArrayList<SelfSiteRequest>(
			soapModels.length);

		for (SelfSiteRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SelfSiteRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _selfSiteRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSelfSiteRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _selfSiteRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SelfSiteRequest.class;
	}

	@Override
	public String getModelClassName() {
		return SelfSiteRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SelfSiteRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SelfSiteRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SelfSiteRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SelfSiteRequest)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SelfSiteRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SelfSiteRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SelfSiteRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SelfSiteRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SelfSiteRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SelfSiteRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SelfSiteRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SelfSiteRequest, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<SelfSiteRequest, Object>>();
		Map<String, BiConsumer<SelfSiteRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SelfSiteRequest, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", SelfSiteRequest::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<SelfSiteRequest, Long>)SelfSiteRequest::setMvccVersion);
		attributeGetterFunctions.put("uuid", SelfSiteRequest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setUuid);
		attributeGetterFunctions.put(
			"selfSiteRequestId", SelfSiteRequest::getSelfSiteRequestId);
		attributeSetterBiConsumers.put(
			"selfSiteRequestId",
			(BiConsumer<SelfSiteRequest, Long>)
				SelfSiteRequest::setSelfSiteRequestId);
		attributeGetterFunctions.put("groupId", SelfSiteRequest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SelfSiteRequest, Long>)SelfSiteRequest::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SelfSiteRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SelfSiteRequest, Long>)SelfSiteRequest::setCompanyId);
		attributeGetterFunctions.put("userId", SelfSiteRequest::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SelfSiteRequest, Long>)SelfSiteRequest::setUserId);
		attributeGetterFunctions.put("userName", SelfSiteRequest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setUserName);
		attributeGetterFunctions.put(
			"createDate", SelfSiteRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SelfSiteRequest, Date>)SelfSiteRequest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SelfSiteRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SelfSiteRequest, Date>)
				SelfSiteRequest::setModifiedDate);
		attributeGetterFunctions.put("email", SelfSiteRequest::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setEmail);
		attributeGetterFunctions.put("lastName", SelfSiteRequest::getLastName);
		attributeSetterBiConsumers.put(
			"lastName",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setLastName);
		attributeGetterFunctions.put(
			"firstName", SelfSiteRequest::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setFirstName);
		attributeGetterFunctions.put("phone", SelfSiteRequest::getPhone);
		attributeSetterBiConsumers.put(
			"phone",
			(BiConsumer<SelfSiteRequest, String>)SelfSiteRequest::setPhone);
		attributeGetterFunctions.put(
			"projectTitle", SelfSiteRequest::getProjectTitle);
		attributeSetterBiConsumers.put(
			"projectTitle",
			(BiConsumer<SelfSiteRequest, String>)
				SelfSiteRequest::setProjectTitle);
		attributeGetterFunctions.put(
			"projectDescription", SelfSiteRequest::getProjectDescription);
		attributeSetterBiConsumers.put(
			"projectDescription",
			(BiConsumer<SelfSiteRequest, String>)
				SelfSiteRequest::setProjectDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSelfSiteRequestId() {
		return _selfSiteRequestId;
	}

	@Override
	public void setSelfSiteRequestId(long selfSiteRequestId) {
		_columnBitmask = -1L;

		_selfSiteRequestId = selfSiteRequestId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@JSON
	@Override
	public String getPhone() {
		if (_phone == null) {
			return "";
		}
		else {
			return _phone;
		}
	}

	@Override
	public void setPhone(String phone) {
		_phone = phone;
	}

	@JSON
	@Override
	public String getProjectTitle() {
		if (_projectTitle == null) {
			return "";
		}
		else {
			return _projectTitle;
		}
	}

	@Override
	public void setProjectTitle(String projectTitle) {
		_projectTitle = projectTitle;
	}

	@JSON
	@Override
	public String getProjectDescription() {
		if (_projectDescription == null) {
			return "";
		}
		else {
			return _projectDescription;
		}
	}

	@Override
	public void setProjectDescription(String projectDescription) {
		_projectDescription = projectDescription;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SelfSiteRequest.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SelfSiteRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SelfSiteRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SelfSiteRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SelfSiteRequestImpl selfSiteRequestImpl = new SelfSiteRequestImpl();

		selfSiteRequestImpl.setMvccVersion(getMvccVersion());
		selfSiteRequestImpl.setUuid(getUuid());
		selfSiteRequestImpl.setSelfSiteRequestId(getSelfSiteRequestId());
		selfSiteRequestImpl.setGroupId(getGroupId());
		selfSiteRequestImpl.setCompanyId(getCompanyId());
		selfSiteRequestImpl.setUserId(getUserId());
		selfSiteRequestImpl.setUserName(getUserName());
		selfSiteRequestImpl.setCreateDate(getCreateDate());
		selfSiteRequestImpl.setModifiedDate(getModifiedDate());
		selfSiteRequestImpl.setEmail(getEmail());
		selfSiteRequestImpl.setLastName(getLastName());
		selfSiteRequestImpl.setFirstName(getFirstName());
		selfSiteRequestImpl.setPhone(getPhone());
		selfSiteRequestImpl.setProjectTitle(getProjectTitle());
		selfSiteRequestImpl.setProjectDescription(getProjectDescription());

		selfSiteRequestImpl.resetOriginalValues();

		return selfSiteRequestImpl;
	}

	@Override
	public int compareTo(SelfSiteRequest selfSiteRequest) {
		int value = 0;

		if (getSelfSiteRequestId() < selfSiteRequest.getSelfSiteRequestId()) {
			value = -1;
		}
		else if (getSelfSiteRequestId() >
					selfSiteRequest.getSelfSiteRequestId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(
			getCreateDate(), selfSiteRequest.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SelfSiteRequest)) {
			return false;
		}

		SelfSiteRequest selfSiteRequest = (SelfSiteRequest)object;

		long primaryKey = selfSiteRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SelfSiteRequest> toCacheModel() {
		SelfSiteRequestCacheModel selfSiteRequestCacheModel =
			new SelfSiteRequestCacheModel();

		selfSiteRequestCacheModel.mvccVersion = getMvccVersion();

		selfSiteRequestCacheModel.uuid = getUuid();

		String uuid = selfSiteRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			selfSiteRequestCacheModel.uuid = null;
		}

		selfSiteRequestCacheModel.selfSiteRequestId = getSelfSiteRequestId();

		selfSiteRequestCacheModel.groupId = getGroupId();

		selfSiteRequestCacheModel.companyId = getCompanyId();

		selfSiteRequestCacheModel.userId = getUserId();

		selfSiteRequestCacheModel.userName = getUserName();

		String userName = selfSiteRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			selfSiteRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			selfSiteRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			selfSiteRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			selfSiteRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			selfSiteRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		selfSiteRequestCacheModel.email = getEmail();

		String email = selfSiteRequestCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			selfSiteRequestCacheModel.email = null;
		}

		selfSiteRequestCacheModel.lastName = getLastName();

		String lastName = selfSiteRequestCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			selfSiteRequestCacheModel.lastName = null;
		}

		selfSiteRequestCacheModel.firstName = getFirstName();

		String firstName = selfSiteRequestCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			selfSiteRequestCacheModel.firstName = null;
		}

		selfSiteRequestCacheModel.phone = getPhone();

		String phone = selfSiteRequestCacheModel.phone;

		if ((phone != null) && (phone.length() == 0)) {
			selfSiteRequestCacheModel.phone = null;
		}

		selfSiteRequestCacheModel.projectTitle = getProjectTitle();

		String projectTitle = selfSiteRequestCacheModel.projectTitle;

		if ((projectTitle != null) && (projectTitle.length() == 0)) {
			selfSiteRequestCacheModel.projectTitle = null;
		}

		selfSiteRequestCacheModel.projectDescription = getProjectDescription();

		String projectDescription =
			selfSiteRequestCacheModel.projectDescription;

		if ((projectDescription != null) &&
			(projectDescription.length() == 0)) {

			selfSiteRequestCacheModel.projectDescription = null;
		}

		return selfSiteRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SelfSiteRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SelfSiteRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SelfSiteRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SelfSiteRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SelfSiteRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SelfSiteRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SelfSiteRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SelfSiteRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SelfSiteRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SelfSiteRequest.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _selfSiteRequestId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _email;
	private String _lastName;
	private String _firstName;
	private String _phone;
	private String _projectTitle;
	private String _projectDescription;
	private long _columnBitmask;
	private SelfSiteRequest _escapedModel;

}